name: Clojure CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin' # See 'Supported distributions' for available options
        java-version: '21'
    - uses: DeLaGuardo/setup-clojure@11.0
      with:
        lein: 'latest'
        cljfmt: 'latest'
    - name: Cache clojure dependencies
      uses: actions/cache@v3
      with:
        path: |
          ~/.m2/repository
          ~/.gitlibs
          ~/.deps.clj
        # List all files containing dependencies:
        key: cljdeps-${{ hashFiles('project.clj') }}
        restore-keys: cljdeps-
    - name: check format
      run: |
        cd http3
        cljfmt check
        cd http2
        cljfmt check
        cd ..
        cljfmt check
    - name: Install http2
      run: |
        cd http2
        lein test
        lein install
    - name: Install http3
      run: |
        cd http3
        lein test
        lein install
    - name: Run tests
      run: lein test
